import { useEffect, useRef, useState } from "react";
import PublicNav from "@/components/PublicNav";
import PublicFooter from "@/components/PublicFooter";
import FAQSection from "@/components/FAQSection";
import { ArrowRight, Check, Clock3, ClipboardCheck, Headset, PackageCheck, Phone, ShieldCheck, Truck, Users, Warehouse } from "lucide-react";

const revealClass = "log-reveal";
function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const node = ref.current;
    if (!node || !("IntersectionObserver" in window)) return;
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) { node.classList.add("is-visible"); observer.disconnect(); }
    }, { threshold: 0.12 });
    observer.observe(node);
    return () => observer.disconnect();
  }, []);
  return <div ref={ref} className={`${revealClass} ${className}`}>{children}</div>;
}

const jobs = [
  { icon: PackageCheck, title: "Orderpickers", text: "Nauwkeurig verzamelen, scannen en klaarzetten. Mensen die tempo houden zonder de laatste controle over te slaan.", tags: ["Pick & pack", "Voice-picking", "Avondploeg"] },
  { icon: Warehouse, title: "Magazijnmedewerkers", text: "Van inbound tot voorraadbeheer: praktisch ingesteld en snel wegwijs in jouw magazijn.", tags: ["Inbound", "Outbound", "Voorraad"] },
  { icon: Truck, title: "Heftruckchauffeurs", text: "Gecertificeerde chauffeurs voor veilig laden, lossen en intern transport wanneer het echt door moet.", tags: ["Reachtruck", "EPT", "Laden & lossen"] },
  { icon: ClipboardCheck, title: "Inpakkers", text: "Zorgvuldig verpakken, controleren en labelen. Ook als de band blijft lopen.", tags: ["Verpakken", "Kwaliteitscheck", "Productie"] },
  { icon: Truck, title: "Expeditie", text: "De laatste meters voor vertrek: zendingen compleet, docks op orde en chauffeurs goed geholpen.", tags: ["Dockplanning", "Zendingen", "Pallets"] },
  { icon: Clock3, title: "Piek- en ploegenteams", text: "Extra handen voor seizoenspieken, nachtdiensten of onverwachte uitval. Op- en afschalen zonder ruis.", tags: ["Piekdrukte", "Nacht", "Vaste poule"] },
];

const faqs = [
  { q: "Hoe snel kunnen jullie logistiek personeel leveren?", a: "We schakelen snel. Na jouw aanvraag bespreken we de planning, functie en eisen en zoeken we een passende medewerker uit onze vaste poule. Bij spoed kijken we direct wat er beschikbaar is." },
  { q: "Leveren jullie ook heftruckchauffeurs?", a: "Ja. We kunnen logistieke medewerkers inzetten met ervaring op reachtruck, heftruck, EPT en in expeditie. Geef in je aanvraag aan welke certificaten en machines nodig zijn." },
  { q: "Zijn medewerkers bij EXTRA in loondienst?", a: "Ja, onze medewerkers zijn bij EXTRA in loondienst. EXTRA is geregistreerd volgens NEN 4400-1. Dat betekent duidelijkheid over werkgeverschap en minder risico voor jouw organisatie." },
  { q: "Kan ik een vaste poule opbouwen?", a: "Zeker. We houden bij wie goed past bij jouw locatie, ploeg en werktempo. Zo groeit er een vaste poule met vertrouwde gezichten die jouw processen kent." },
  { q: "Is dagbetaling mogelijk voor medewerkers?", a: "Ja, dagbetaling is mogelijk. Dat helpt ons om goede logistieke medewerkers aan te trekken en betrokken te houden, terwijl jij op een betrouwbare bezetting kunt rekenen." },
];

export default function LogistiekPersoneelInhuren() {
  const [openStep, setOpenStep] = useState(0);
  useEffect(() => {
    document.title = "Logistiek personeel inhuren | Gescreend & flexibel | EXTRA";
    const description = "Logistiek personeel inhuren? EXTRA levert gescreende magazijnmedewerkers, orderpickers en heftruckchauffeurs in loondienst. Vraag direct aan.";
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) { meta = document.createElement("meta"); meta.setAttribute("name", "description"); document.head.appendChild(meta); }
    meta.setAttribute("content", description);
  }, []);
  return (
    <div className="log-page">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
        .log-page{--ink:#12343b;--cyan:#61c9e0;--cyan-dark:#087c8d;--pale:#e7fbfb;--lime:#d8f36d;--line:#b8e5e7;background:#f8ffff;color:var(--ink);font-family:'DM Sans',sans-serif}
        .log-page h1,.log-page h2,.log-page h3{font-family:'Space Grotesk',sans-serif;letter-spacing:-.045em}.log-page h1{font-size:clamp(2.6rem,6vw,5.8rem);line-height:.96}.log-page h2{font-size:clamp(2.1rem,4.5vw,4.2rem);line-height:1}.log-page section{position:relative;overflow:hidden}.log-wrap{width:min(1160px,calc(100% - 40px));margin:auto}.log-btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;border-radius:999px;padding:15px 23px;font-weight:700;transition:transform .2s,background-color .2s,box-shadow .2s}.log-btn:hover{transform:translateY(-3px)}.log-btn:focus-visible,.log-page button:focus-visible,.log-page a:focus-visible{outline:3px solid #f4a51c;outline-offset:4px}.log-reveal{opacity:0;transform:translateY(24px);transition:opacity .7s ease,transform .7s ease}.log-reveal.is-visible{opacity:1;transform:none}.log-x{position:absolute;pointer-events:none;background:var(--cyan);opacity:.16;mask:url('/images/logistiek-x-patroon.png') center/contain no-repeat;-webkit-mask:url('/images/logistiek-x-patroon.png') center/contain no-repeat}.log-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.log-card{background:#fff;border:1px solid var(--line);padding:25px;border-radius:18px;transition:transform .2s,border-color .2s,box-shadow .2s}.log-card:hover{transform:translateY(-5px);border-color:var(--cyan);box-shadow:0 12px 0 rgba(24,199,213,.12)}.log-label{display:inline-flex;align-items:center;gap:8px;color:var(--cyan-dark);font-size:.76rem;font-weight:700;text-transform:uppercase;letter-spacing:.13em}.log-stat{border-left:3px solid var(--cyan);padding-left:15px}.log-step{border-left:2px solid #b6dfe0;padding:0 0 28px 25px;position:relative}.log-step:before{content:'';position:absolute;left:-9px;top:0;width:16px;height:16px;background:var(--lime);border:3px solid var(--ink);border-radius:50%}.log-step.active{border-color:var(--cyan-dark)}.log-step button{text-align:left}.log-page .faq-log{background:var(--pale)}@media(max-width:767px){.log-wrap{width:min(100% - 32px,600px)}.log-grid{grid-template-columns:1fr}.log-page h1{font-size:clamp(2.8rem,13vw,4.5rem)}}@media(prefers-reduced-motion:reduce){.log-reveal{opacity:1;transform:none;transition:none}.log-btn,.log-card{transition:none}}
      `}</style>
      <PublicNav forceDark />
      <section className="min-h-[720px] flex items-center bg-[#61c9e0]">
        <div className="log-x w-[560px] h-[560px] -left-32 top-8 -rotate-12" style={{backgroundColor:"#8ae0e4",opacity:.3}}/>
        <div className="log-x w-[450px] h-[450px] left-[28%] bottom-[-210px] rotate-[25deg]" style={{backgroundColor:"#969ce1",opacity:.22}}/>
        <div className="log-x w-[340px] h-[340px] right-0 top-14 rotate-[18deg]" style={{backgroundColor:"#b3e7e7",opacity:.34}}/>
        <div className="log-wrap grid lg:grid-cols-[1.02fr_.98fr] gap-8 items-center pt-28 pb-16 relative z-10">
          <div className="relative min-h-[520px] order-2 lg:order-1"><div className="log-x w-[430px] h-[430px] -left-16 top-10 rotate-[16deg]" style={{backgroundColor:"#7163dd",opacity:.26}}/><img src="/images/logistiek-medewerker.webp" alt="Logistiek medewerker in een geel veiligheidsvest" className="absolute bottom-[-76px] left-[3%] h-[605px] w-auto max-w-none object-contain z-10" loading="eager"/><div className="absolute left-0 top-8 bg-white px-5 py-4 rounded-2xl shadow-lg z-20 font-bold"><span className="text-2xl block">24/7</span><span className="text-xs text-[#087c8d]">operationeel bereikbaar</span></div></div>
          <div className="order-1 lg:order-2"><div className="max-w-xl lg:ml-auto"><div className="flex flex-wrap gap-2 mb-7"><span className="bg-[#d8f36d] px-4 py-2 rounded-full text-xs font-bold uppercase tracking-wider">Logistiek personeel</span><span className="bg-white/25 px-4 py-2 rounded-full text-xs font-bold uppercase tracking-wider">NEN 4400-1</span></div><h1 className="text-white">Als het druk wordt,<br/><span className="text-[#12343b]">staan wij klaar.</span></h1><p className="text-lg sm:text-xl text-[#12343b]/85 max-w-lg mt-7 leading-relaxed">Gescreende magazijnmedewerkers, orderpickers en heftruckchauffeurs die jouw operatie begrijpen. Snel inzetbaar, persoonlijk geselecteerd en in loondienst bij EXTRA.</p><div className="flex flex-col sm:flex-row gap-3 mt-9"><a className="log-btn bg-white text-[#087c8d] hover:bg-[#f8ffff]" href="/personeelsaanvraag">Vraag personeel aan <ArrowRight size={18}/></a><a className="log-btn border-2 border-white text-white hover:bg-white/15" href="tel:0851305915">Bel ons direct <ArrowRight size={18}/></a></div><div className="flex flex-wrap gap-5 mt-9 text-sm font-semibold"><span><Check size={17} className="inline mr-1"/>Iedereen in loondienst</span><span><Check size={17} className="inline mr-1"/>Dagbetaling mogelijk</span><span><Check size={17} className="inline mr-1"/>Vaste poule</span></div></div></div>
        </div>
        <p className="absolute right-8 bottom-7 text-xs sm:text-sm font-semibold text-white/90 z-10"><strong>EXTRA</strong> — Het uitzendbureau dat werkt</p>
      </section>

      <section id="functies" className="py-24 sm:py-32 bg-[#f8ffff]"><div className="log-wrap"><Reveal><div className="max-w-2xl mb-14"><span className="log-label"><Warehouse size={16}/> Functies</span><h2 className="mt-5">Mensen die de goederenstroom laten lopen.</h2><p className="mt-5 text-lg text-[#45666b]">Van de eerste pallet tot het laatste label. Jij vertelt waar de druk zit, wij brengen de juiste handen en het juiste tempo.</p></div></Reveal><div className="log-grid">{jobs.map((job,i)=><Reveal key={job.title}><article className="log-card h-full"><div className="w-12 h-12 bg-[#d8f36d] rounded-xl flex items-center justify-center mb-5"><job.icon size={24}/></div><h3 className="text-2xl">{job.title}</h3><p className="text-[#45666b] leading-relaxed mt-3">{job.text}</p><div className="flex flex-wrap gap-2 mt-5">{job.tags.map(t=><span key={t} className="text-xs font-semibold border border-[#b8e5e7] rounded-full px-3 py-1">{t}</span>)}</div></article></Reveal>)}</div></div></section>

      <section id="waarom-extra" className="py-24 sm:py-32 bg-[#e7fbfb]"><div className="log-x w-72 h-72 right-[-60px] top-16" style={{backgroundColor:"var(--cyan-dark)"}}/><div className="log-wrap"><Reveal><div className="max-w-2xl mb-12"><span className="log-label"><ShieldCheck size={16}/> Waarom EXTRA</span><h2 className="mt-5">Geen cv's stapelen.<br/>Wel rust op de vloer.</h2></div></Reveal><div className="grid md:grid-cols-2 gap-x-16 gap-y-8">{["Persoonlijk gescreend","Eén aanspreekpunt","Vaste poule per locatie","Flexibel op- en afschalen","NEN 4400-1 gecertificeerd","Medewerkers in loondienst"].map((t,i)=><Reveal key={t}><div className="flex gap-4 border-b border-[#b8e5e7] pb-6"><span className="font-mono text-sm text-[#087c8d]">0{i+1}</span><div><h3 className="text-xl tracking-[-.02em]">{t}</h3><p className="text-[#45666b] mt-2">{["We spreken iedere kandidaat zelf en toetsen ervaring, houding en beschikbaarheid.","Korte lijnen met een team dat de hectiek van logistiek kent.","Dezelfde betrouwbare mensen leren jouw locatie en werkwijze kennen.","Van een extra ploeg in november tot structurele bezetting.","Duidelijk werkgeverschap en betrouwbare administratie.","Dagbetaling mogelijk voor medewerkers die daarvoor kiezen."][i]}</p></div></div></Reveal>)}</div></div></section>

      <section className="py-16 bg-white border-y border-[#b8e5e7]"><div className="log-wrap"><p className="text-center text-xs uppercase tracking-[.18em] font-bold text-[#6a898d] mb-8">Werkbaar voor distributiecentra, productiebedrijven en e-commerce</p><div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center font-bold text-[#12343b]/65"><span className="py-5 border border-[#b8e5e7] rounded-xl">FULFILMENT</span><span className="py-5 border border-[#b8e5e7] rounded-xl">DISTRIBUTIE</span><span className="py-5 border border-[#b8e5e7] rounded-xl">PRODUCTIE</span><span className="py-5 border border-[#b8e5e7] rounded-xl">RETAIL</span></div></div></section>

      <section className="py-24 sm:py-32 bg-[#12343b] text-white"><div className="log-wrap grid lg:grid-cols-[.8fr_1.2fr] gap-14 items-center"><Reveal><span className="log-label !text-[#d8f36d]">Klantcase · distributie</span><h2 className="mt-5">De piek halen zonder je team op te branden.</h2><p className="text-white/70 text-lg mt-6 leading-relaxed">Een e-commerce opdrachtgever had in de avonduren structureel extra orderpickers nodig. EXTRA bouwde een vaste poule op: medewerkers die terugkomen, de werkwijze kennen en elkaar aanvullen.</p><a href="/personeelsaanvraag" className="log-btn bg-[#d8f36d] text-[#12343b] mt-8">Bespreek jouw piek <ArrowRight size={18}/></a></Reveal><Reveal><div className="grid grid-cols-2 gap-4"><div className="bg-white/10 rounded-2xl p-6"><span className="text-5xl font-bold text-[#d8f36d]">42</span><p className="mt-2 text-white/65">medewerkers in vaste poule</p></div><div className="bg-white/10 rounded-2xl p-6"><span className="text-5xl font-bold text-[#d8f36d]">3</span><p className="mt-2 text-white/65">ploegen per week</p></div><div className="col-span-2 border-l-2 border-[#18c7d5] pl-6 py-3 text-lg">“Dezelfde gezichten op de vloer geeft onze teamleiders eindelijk overzicht.”<span className="block text-sm text-white/50 mt-2">— Operations manager, Amsterdam</span></div></div></Reveal></div></section>

      <section className="py-24 sm:py-32 bg-[#f8ffff]"><div className="log-wrap grid md:grid-cols-2 gap-14 items-center"><Reveal><span className="log-label"><Users size={16}/> Persoonlijk gescreend</span><h2 className="mt-5">Een medewerker is meer dan een profiel.</h2><p className="text-lg text-[#45666b] mt-6 leading-relaxed">We spreken kandidaten persoonlijk, checken werkervaring en beschikbaarheid en bespreken wat er op jouw locatie nodig is. Zo weet je wie er binnenkomt vóór de eerste shift begint.</p><div className="grid grid-cols-2 gap-6 mt-9"><div className="log-stat"><strong className="text-xl block">Persoonlijk</strong><span className="text-sm text-[#45666b]">gesprek vooraf</span></div><div className="log-stat"><strong className="text-xl block">Passend</strong><span className="text-sm text-[#45666b]">bij jouw ploeg</span></div></div></Reveal><Reveal><div className="bg-[#d8f36d] rounded-[30px] p-8 sm:p-12 rotate-2"><div className="bg-white rounded-2xl p-6 -rotate-2 shadow-sm"><p className="text-xs uppercase font-bold tracking-widest text-[#087c8d]">EXTRA selectiekaart</p><div className="flex items-center gap-4 mt-6"><div className="w-14 h-14 rounded-full bg-[#18c7d5] flex items-center justify-center font-bold text-xl">MK</div><div><strong className="block">Milan K.</strong><span className="text-sm text-[#45666b]">Orderpicker · avondploeg</span></div></div><div className="border-t border-[#b8e5e7] mt-6 pt-5 space-y-3 text-sm"><p><Check size={16} className="inline mr-2 text-[#087c8d]"/>Ervaring met voice-picking</p><p><Check size={16} className="inline mr-2 text-[#087c8d]"/>Beschikbaar vanaf 16:00</p><p><Check size={16} className="inline mr-2 text-[#087c8d]"/>Persoonlijk gesproken door EXTRA</p></div></div></div></Reveal></div></section>

      <section className="py-20 bg-[#dff7f7]"><div className="log-wrap grid grid-cols-2 md:grid-cols-4 gap-8"><Reveal><div className="log-stat"><strong className="text-4xl font-bold">8.7</strong><p className="text-sm mt-2">gemiddelde klantwaardering</p></div></Reveal><Reveal><div className="log-stat"><strong className="text-4xl font-bold">91%</strong><p className="text-sm mt-2">komt terug op volgende shift</p></div></Reveal><Reveal><div className="log-stat"><strong className="text-4xl font-bold">1</strong><p className="text-sm mt-2">vast aanspreekpunt</p></div></Reveal><Reveal><div className="log-stat"><strong className="text-4xl font-bold">24/7</strong><p className="text-sm mt-2">bereikbaar bij uitval</p></div></Reveal></div></section>

      <section className="py-24 sm:py-32 bg-white"><div className="log-wrap grid md:grid-cols-2 gap-14"><Reveal><span className="log-label"><Headset size={16}/> Vaste gezichten</span><h2 className="mt-5">De poule die jouw locatie kent.</h2><p className="text-lg text-[#45666b] mt-6">Goede logistiek draait op ritme. Daarom bouwen we niet aan een eindeloze lijst, maar aan een poule van mensen die passen bij jouw werkvloer.</p><a href="tel:0851305915" className="log-btn bg-[#18c7d5] text-[#12343b] mt-8">Bel met ons team <Phone size={18}/></a></Reveal><Reveal><div className="grid grid-cols-2 gap-3"><div className="bg-[#12343b] text-white p-6 rounded-2xl col-span-2"><strong className="text-2xl">Jouw locatie</strong><p className="text-white/60 mt-2">De juiste mensen, opnieuw en opnieuw.</p></div><div className="bg-[#e7fbfb] p-6 rounded-2xl"><Users size={24}/><p className="font-bold mt-6">Bekende gezichten</p></div><div className="bg-[#d8f36d] p-6 rounded-2xl"><Truck size={24}/><p className="font-bold mt-6">Minder uitleg</p></div></div></Reveal></div></section>

      <section className="py-24 sm:py-32 bg-[#e7fbfb]"><div className="log-wrap grid md:grid-cols-2 gap-14"><Reveal><span className="log-label"><ClipboardCheck size={16}/> Selectieproces</span><h2 className="mt-5">Van aanvraag naar eerste shift.</h2><p className="mt-5 text-[#45666b]">Duidelijk proces, korte lijnen. Klik op een stap voor de details.</p><div className="mt-9">{["Jij vertelt wat nodig is","Wij selecteren en stellen voor","De planning staat","Wij blijven bereikbaar"].map((s,i)=><div className={`log-step ${openStep===i?"active":""}`} key={s}><button className="w-full" onClick={()=>setOpenStep(i)}><strong className="text-lg">{s}</strong>{openStep===i&&<p className="text-[#45666b] mt-2">{["Functie, ploeg, locatie en gewenste startdatum.","Een passende medewerker uit onze poule, met relevante ervaring.","Bevestiging en duidelijke afspraken voor medewerker en locatie.","Ook tijdens de shift kun je direct met ons schakelen."][i]}</p>}</button></div>)}</div></Reveal><Reveal><div className="bg-white rounded-3xl p-8 sm:p-12 border border-[#b8e5e7]"><p className="text-xs uppercase tracking-widest font-bold text-[#087c8d]">Voor jouw planning</p><h3 className="text-3xl mt-5">Eén aanvraag.<br/>Een ploeg die staat.</h3><div className="mt-8 space-y-4 text-[#45666b]">{["Snel een eerste voorstel","Heldere afspraken vooraf","Geen zzp-risico's","Eén factuur, één partner"].map(t=><p key={t}><Check size={18} className="inline mr-3 text-[#087c8d]"/>{t}</p>)}</div></div></Reveal></div></section>

      <section className="py-24 sm:py-32 bg-[#f8ffff]"><div className="log-wrap grid md:grid-cols-2 gap-12 items-center"><Reveal><span className="log-label">EXTRAATje</span><h2 className="mt-5">Goed werk mag gezien worden.</h2><p className="text-lg text-[#45666b] mt-6">Met EXTRAATje belonen we medewerkers voor hun inzet. Dat maakt het aantrekkelijk om terug te komen — en helpt jou aan mensen die betrokken blijven.</p></Reveal><Reveal><div className="bg-[#12343b] text-white rounded-3xl p-8"><div className="flex items-center justify-between border-b border-white/15 pb-5"><strong className="text-2xl">EXTRAATje</strong><span className="text-[#d8f36d] font-bold">+ 120 punten</span></div><div className="py-6"><p className="text-white/60 text-sm">Voor een foutloze week</p><div className="h-3 bg-white/15 rounded-full mt-3"><div className="h-3 bg-[#d8f36d] rounded-full w-[76%]"/></div></div><p className="text-sm text-white/60">Medewerkers die zich gewaardeerd voelen, bouwen mee aan jouw vaste poule.</p></div></Reveal></div></section>

      <div className="faq-log"><FAQSection heading="Vragen over logistiek personeel" faqs={faqs}/></div>
      <section className="py-28 bg-[#18c7d5] text-center relative"><div className="log-x w-80 h-80 left-[-70px] top-4" style={{backgroundColor:"var(--lime)"}}/><div className="log-wrap relative z-10"><Reveal><span className="log-label !text-[#12343b]">Klaar voor de volgende shift?</span><h2 className="mt-5 text-[#12343b]">Zet vandaag de eerste stap.</h2><p className="text-lg text-[#12343b]/75 max-w-xl mx-auto mt-5">Vertel ons waar jouw operatie extra kracht kan gebruiken. We nemen binnen één werkdag contact op.</p><div className="flex flex-col sm:flex-row justify-center gap-3 mt-9"><a className="log-btn bg-[#12343b] text-white" href="/personeelsaanvraag">Personeel aanvragen <ArrowRight size={18}/></a><a className="log-btn bg-white text-[#12343b]" href="tel:0851305915"><Phone size={18}/>Bel 085 - 130 59 15</a></div></Reveal></div></section>
      <PublicFooter />
    </div>
  );
}